version: "3.9"
services:

  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_DB: "account"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

    ports:
      - "5432:5432"